spring.application.name=accountCards
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=customers;encrypt=false;
spring.datasource.username=userDEV
spring.datasource.password=password123
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update